## Numpy 기초 연습 문제

In [1]:
import numpy as np

#### 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이때 생성된 ndarray의 이름은 a가 되도록 한다

In [2]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

In [3]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] = i*4 + j + 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [4]:
num = 1
for i in range(a.shape[0]): #shape[0] 은 행. 즉, i =3 행
    for j in range(a.shape[1]): #shape[1] 은 열. j = 4 열
        a[i, j] =  num # i와 j 하나씩 채우기
        num += 1 


#### 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [5]:
a[1, 2] # 2행 3열

7.0

#### 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

In [6]:
a.shape # a의 크기 확인

(3, 4)

In [7]:
a[[1], :] # 두번째 행만 슬라이싱

array([[5., 6., 7., 8.]])

#### 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

In [8]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result
# if문을 사용하여 6보다 작은 i가 3, j가 4인 행렬을 나타내라

array([1., 2., 3., 4., 5., 6.])

In [9]:
a[a <= 6] # 불린인덱싱을 사용하여 간편하게 나타냄

array([1., 2., 3., 4., 5., 6.])

#### 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [10]:
b = np.random.random((3, 4)) # 랜덤으로 3행 4열의 ndarray 생성
b

array([[0.04701714, 0.42724   , 0.13566936, 0.5249124 ],
       [0.90451758, 0.05286867, 0.4736382 , 0.13393057],
       [0.60693554, 0.23402675, 0.62414835, 0.74872405]])

#### 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [11]:
c = a * b
c

array([[0.04701714, 0.85448   , 0.40700809, 2.09964962],
       [4.5225879 , 0.31721201, 3.3154674 , 1.07144454],
       [5.46241983, 2.34026747, 6.86563187, 8.98468865]])

#### 9. b의 전치행렬을 구하여 d에 저장하시오.

In [12]:
d = b.T #.Transpose
d

array([[0.04701714, 0.90451758, 0.60693554],
       [0.42724   , 0.05286867, 0.23402675],
       [0.13566936, 0.4736382 , 0.62414835],
       [0.5249124 , 0.13393057, 0.74872405]])

In [13]:
d.shape

(4, 3)

#### 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [14]:
print(a.shape, d.shape)

(3, 4) (4, 3)


#### 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [15]:
e = a.dot(d)
e

array([[ 3.40815485,  2.96689179,  5.9423303 ],
       [ 7.94751046,  9.22671185, 14.79766906],
       [12.48686608, 15.48653191, 23.65300782]])

#### 12. e에 대하여 각 열의 합을 계산하시오.

In [16]:
np.sum(e, axis=1) # 1은 열이므로, 열의 sum을 구해라

array([12.31737694, 31.97189138, 51.62640582])

## Pandas 기초 연습 문제

In [17]:
import pandas as pd

#### 1. 딕셔너리를 이용하여 아래와 같은 모양이 되도록 data frame을 생성하시오.

In [18]:
score={'학번':[201524213,201621223,201621233, 201611111, 201722222],
       '이름':['오지환','박용택','정성훈', '다니엘', '지민'],
       '학과':['경영정보','경영정보','경영정보','컴퓨터공학','컴퓨터공학'],
       'Quiz':[15,20,10,17,18],
       '중간고사':[20,20,15,18,16]}

df= pd.DataFrame(score)
df

학번   이름     학과  Quiz  중간고사
0  201524213  오지환   경영정보    15    20
1  201621223  박용택   경영정보    20    20
2  201621233  정성훈   경영정보    10    15
3  201611111  다니엘  컴퓨터공학    17    18
4  201722222   지민  컴퓨터공학    18    16

In [19]:
df['학번'] # '학번' 열 확인

0    201524213
1    201621223
2    201621233
3    201611111
4    201722222
Name: 학번, dtype: int64

#### 2. 위에서 생성한 데이터프레임으로부터 인덱싱을 이용하여 이름과 중간고사를 추출하시오

In [20]:
df[['이름', '중간고사']]

이름  중간고사
0  오지환    20
1  박용택    20
2  정성훈    15
3  다니엘    18
4   지민    16

#### 3. reindex를 이용하여 2, 0, 4, 1, 3 순으로 순서를 변경하시오

In [21]:
df = df.reindex([2, 0, 4, 1, 3]) #원래 0부터 시작하는 인덱스의 데이터프레임을 새로 바꾼 인덱스 순서로 정렬
df

학번   이름     학과  Quiz  중간고사
2  201621233  정성훈   경영정보    10    15
0  201524213  오지환   경영정보    15    20
4  201722222   지민  컴퓨터공학    18    16
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18

#### 4. iloc과 loc을 각각 이용하여 박용택 학생의 record를 추출하시오. (iloc으로 한번, loc으로 한번 수행)

In [22]:
print(df.iloc[3]) # 네 번째에 위치하고 있는 박용택
print(df.loc[1]) # 인덱스가 1번인 박용택 

학번      201621223
이름            박용택
학과           경영정보
Quiz           20
중간고사           20
Name: 1, dtype: object
학번      201621223
이름            박용택
학과           경영정보
Quiz           20
중간고사           20
Name: 1, dtype: object


#### 5. iloc과 loc을 각각 이용하여 모든 학생의 이름과 중간고사 점수를 추출하시오. (iloc으로 한번, loc으로 한번 수행)

In [23]:
print(df.iloc[:, [1, 4]]) # 두 번째, 다섯번 째 열에 있는 모든 정보 빼기 
print(df.loc[:, ['이름', '중간고사']]) # 이름이 위치한 열 추출


    이름  중간고사
2  정성훈    15
0  오지환    20
4   지민    16
1  박용택    20
3  다니엘    18
    이름  중간고사
2  정성훈    15
0  오지환    20
4   지민    16
1  박용택    20
3  다니엘    18


#### 6. 중간고사 점수의 평균을 구하시오.

In [24]:
df['중간고사'].mean()

17.8

#### 7. 중간고사 점수가 가장 낮은 학생의 index를 구하시오.

In [25]:
df['중간고사'].idxmin() # min한 인덱스 추출

2

#### 9. 위 데이터프레임의 각 열에 대해서 개수, 평균, 표준편차, 최소최대값 등의 다양한 통계량을 출력하시오.

In [26]:
df.describe() # 평균, 최대값, 최소값 등 통계량 출력

학번       Quiz       중간고사
count  5.000000e+00   5.000000   5.000000
mean   2.016200e+08  16.000000  17.800000
std    7.018995e+04   3.807887   2.280351
min    2.015242e+08  10.000000  15.000000
25%    2.016111e+08  15.000000  16.000000
50%    2.016212e+08  17.000000  18.000000
75%    2.016212e+08  18.000000  20.000000
max    2.017222e+08  20.000000  20.000000

#### 10. 위 데이터프레임을 중간고사 점수에 따라 내림차순으로 정렬하시오

In [27]:
df.sort_values('중간고사', ascending=False) 

학번   이름     학과  Quiz  중간고사
0  201524213  오지환   경영정보    15    20
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18
4  201722222   지민  컴퓨터공학    18    16
2  201621233  정성훈   경영정보    10    15

#### 11. 학생 중에서 퀴즈 점수가 평균 이상인 학생들의 이름을 출력하시오

In [28]:
quiz_mean = df['Quiz'].mean() #퀴즈 점수 평균
df[df['Quiz'] > quiz_mean]['이름'] # 평균보다 큰 df의 이름만 추출

4     지민
1    박용택
3    다니엘
Name: 이름, dtype: object

#### 12. 학생 중에서 퀴즈와 중간고사 점수 모두 평균 이상인 학생들의 record를 출력하시오

In [29]:
quiz_mean = df['Quiz'].mean() # 퀴즈 평균 구하기
mid_mean = df['중간고사'].mean() # 중간고사 평균 구하기 
df[(df['Quiz'] > quiz_mean) & (df['중간고사'] > mid_mean)] # 둘 다 큰 df구하기,, &로 묶어줌

학번   이름     학과  Quiz  중간고사
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18

### 13. value_counts를 이용하여 학과 별로 학생의 수를 구하시오

In [30]:
df['학과'].value_counts() # 학과 name을 이용하여 추출

경영정보     3
컴퓨터공학    2
Name: 학과, dtype: int64

#### 14. groupby를 이용하여 학과 별로 중간고사의 평균을 구하시오

In [31]:
df.groupby('학과')['중간고사'].mean() # group by를 사용하여 학과로 묶고, 중간고사를 평균냄

학과
경영정보     18.333333
컴퓨터공학    17.000000
Name: 중간고사, dtype: float64

In [32]:
df.mean()

학번      201620000.4
Quiz           16.0
중간고사           17.8
dtype: float64

In [33]:
list(df.groupby('학과')) # 리스트로 나타내기

[('경영정보',           학번   이름    학과  Quiz  중간고사
  2  201621233  정성훈  경영정보    10    15
  0  201524213  오지환  경영정보    15    20
  1  201621223  박용택  경영정보    20    20),
 ('컴퓨터공학',           학번   이름     학과  Quiz  중간고사
  4  201722222   지민  컴퓨터공학    18    16
  3  201611111  다니엘  컴퓨터공학    17    18)]